name: Build EXE with PyInstaller

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (64-bit)
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'   # 强制 64位

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE (onefile)
        run: |
          pyinstaller --onefile --windowed --noconsole ^
            --name "国考数据清洗工具" ^
            --icon icon.ico ^
            excel_gui6.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe-build
          path: dist/*
